### ISSUE TITLE
UTC Timezone

### ISSUE THREAD

**Issue by jackvote** [vizplus/vizplus-bitshares-info#1]
При использовании скрипта на различных серверах или при визуализации в разных приложениях, время получения информации с биржи должно быть общим, поэтому предлагаю.

В settings.json.example добавить разницу во времени сервера с utc
            `"utc_time": +5, `

В bot.py соответственно изменить строку
           ` 'datetime': str(datetime.now()-settings['utc_time']),`

**Comment by lososeg** [comment]
Заменил datetime на time_utc. Теперь у всех будет одинаково.
